### PR TITLE
#11 Use ARM template

### PR DESCRIPTION
**Pull request by gaufung**
Using ARM template to deploy tracer service.

### CODE REVIEW

**Review by Anduin2017 — APPROVED** [review]

**Comment by Anduin2017** [comment]
Wow! That is awesome! Can't wait to try it. Thank you! 💯💯💯

**Comment by gaufung** [comment]
ARM official document is too legacy.  The .Net 5.0 hasn't been the default SDK version which takes me a lot of time to figure out the failure.  Azure portal error log is too abstract.

**Comment by Anduin2017** [comment]
Maybe we can help them update the document.

By the way, while you are debugging, you can use any subscription in the Aiursoft AAD.

**Comment by gaufung** [comment]
No. I used my personal Azure subscription.

**Comment by gaufung** [comment]
It looks like failed to pass the CI at the **test** task. @Anduin2017  could you take a look? I don't have permission to kick it off again.

**Comment by Anduin2017** [comment]
No worry. I will check.

**Comment by Anduin2017** [comment]
Seems an official Nuget server-side issue.

Log:

```log
Starting: dotnet test
==============================================================================
Task         : .NET Core
Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
Version      : 2.179.2
Author       : Microsoft Corporation
Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
==============================================================================
C:\windows\system32\chcp.com 65001
Active code page: 65001
Info: .NET Core SDK/runtime 2.2 and 3.0 are now End of Life(EOL) and have been removed from all hosted agents. If you're using these SDK/runtimes on hosted agents, kindly upgrade to newer versions which are not EOL, or else use UseDotNet task to install the required version.
C:\hostedtoolcache\windows\dotnet\dotnet.exe test --logger trx --results-directory D:\a\_temp --configuration Release --collect "Code coverage"

Welcome to .NET 5.0!
---------------------
SDK Version: 5.0.101

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
  Determining projects to restore...
D:\a\1\s\tests\Tracer.Tests.csproj : error NU1101: Unable to find package AngleSharp. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\1\s\Tracer.sln]
D:\a\1\s\tests\Tracer.Tests.csproj : error NU1102: Unable to find package Microsoft.NET.Test.Sdk with version (>= 16.8.3) [D:\a\1\s\Tracer.sln]
D:\a\1\s\tests\Tracer.Tests.csproj : error NU1102:   - Found 1 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 16.6.1 ] [D:\a\1\s\Tracer.sln]
D:\a\1\s\tests\Tracer.Tests.csproj : error NU1102: Unable to find package MSTest.TestAdapter with version (>= 2.1.2) [D:\a\1\s\Tracer.sln]
D:\a\1\s\tests\Tracer.Tests.csproj : error NU1102:   - Found 1 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 2.1.1 ] [D:\a\1\s\Tracer.sln]
D:\a\1\s\tests\Tracer.Tests.csproj : error NU1102: Unable to find package MSTest.TestFramework with version (>= 2.1.2) [D:\a\1\s\Tracer.sln]
D:\a\1\s\tests\Tracer.Tests.csproj : error NU1102:   - Found 1 version(s) in Microsoft Visual Studio Offline Packages [ Nearest version: 2.1.1 ] [D:\a\1\s\Tracer.sln]
D:\a\1\s\tests\Tracer.Tests.csproj : error NU1101: Unable to find package Aiursoft.SDK. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages [D:\a\1\s\Tracer.sln]
  Failed to restore D:\a\1\s\tests\Tracer.Tests.csproj (in 332 ms).
  Restored D:\a\1\s\src\Tracer.csproj (in 1.42 min).
##[error]Error: The process 'C:\hostedtoolcache\windows\dotnet\dotnet.exe' failed with exit code 1
```

**Comment by Anduin2017** [comment]
By the way, I changed the settings to ensure that you have permission to modify our build pipeline.

Have a try at: https://dev.azure.com/aiursoft/Star/_build

**Pull request merged**
