### PR TITLE
Improve views

### PR DESCRIPTION
**Pull request by ganlvtech**
migrate navbar to bootstrap 4
test parts use card component
remove unused css

### CODE REVIEW

**Comment by Anduin2017** [comment]
Thank you so much for your contribution!

**Comment by ganlvtech** [comment]
Is there an auto deployment for this repo? Could a merged PR goes directly and instantly into production server?

**Comment by Anduin2017** [comment]
Nope. Will be published manually tonight.

BTW, the repo was migrated to Azure DevOps.

I will manually merge your pull request here: 

https://aiursoft.visualstudio.com/Tracer

Thanks for your contribution again!

**Comment by Anduin2017** [comment]
@ganlvtech Successfully published by Azure DevOps and running here: http://tracer.aiursoft.com/

That looks so good!

**Pull request merged**
